### ISSUE TITLE
Hang on dumping certain carts

### ISSUE THREAD

**Issue by chancedickson** [citra-emu/uncart#15]
Using uncart to dump OoT3D is hanging at 71% for me, and there is a reported issue of Pokemon Super Mystery Dungeon hanging at 10% as well. Is anyone still working on this project? If not, how do you guys go about debugging programs? I'm willing to at least attempt to fix this bug if I can figure out an appropriate method of debugging.

**Comment by yuriks** [comment]
It's worth trying this branch, @Normmatt says it supposedly fixes a lot of timing-related issues: https://github.com/citra-emu/uncart/pull/10

One thing I did when debugging cart flakiness issues was to add print commands to log all data coming in and out of the cart interface. Some carts were very finicky and required duplicated commands and ignoring of certain responses to work, but that's one of the things that should be fixed by @Normmatt's PR.

**Comment by chncdcksn** [comment]
That worked for my copy of OoT3D! Just waiting on a confirmation that Pokemon Super Mystery Dungeon works with it.

**Comment by fox8091** [comment]
Since this issue is fixed, can it be closed?
